#!/bin/bash
VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1 | tr -d '%')
MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o 'yes')

if [ "$MUTE" = "yes" ]; then
    echo "󰝟 Mute"
elif [ "$VOL" -ge 70 ]; then
    echo "󰕾 ${VOL}%"
elif [ "$VOL" -ge 30 ]; then
    echo "󰖀 ${VOL}%"
else
    echo "󰕿 ${VOL}%"
fi
